# Generated by Django 5.2.2 on 2025-06-11 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailablePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availablepoints', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField()),
                ('points_type', models.CharField(choices=[('GIVE', 'GIVE'), ('TAKE', 'TAKE')], max_length=100)),
                ('appreciation', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_points', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.availablepoints')),
            ],
        ),
    ]
